### To read Suppliers use this API
GET http://localhost:4004/service/ResilienceCockpitService/AlternateSuppliers
Authorization: Basic manager@nexus.com:password

### Use this API to write Data
POST http://localhost:4004/service/ResilienceCockpitService/AlternateSuppliers
Authorization: Basic manager@nexus.com:password
Content-Type: application/json

{
    "supplierNumber": 91,
    "supplierName": "Rosscom Chips",
    "address": "Russia",
    "country_code": "IN",
    "rating": 10,
    "IsActiveEntity": true
}


### Use this for Fetching single entry
GET http://localhost:4004/service/ResilienceCockpitService/AlternateSuppliers(ID='311bdb3e-8d28-41c7-ab71-e7f74dc25ae6',IsActiveEntity=true)
Authorization: Basic manager@nexus.com:password


### Fetch Country for a supplier
GET http://localhost:4004/service/ResilienceCockpitService/AlternateSuppliers(ID='311bdb3e-8d28-41c7-ab71-e7f74dc25ae6',IsActiveEntity=true)/country/descr/$value
Authorization: Basic manager@nexus.com:password

### Update a supplier
PATCH http://localhost:4004/service/ResilienceCockpitService/AlternateSuppliers(ID='1627dd32-170d-47c3-b3d2-07f9a7503196',IsActiveEntity=true)
Authorization: Basic manager@nexus.com:password
Content-Type: application/json

{
    "country_code":"IN"
}

### OData V2 Testing scenario
GET http://localhost:4004/odata/v2/service/ResilienceCockpitService/AlternateSuppliers
Authorization: Basic manager@nexus.com:password



### Trigger Action
POST http://localhost:4004/service/ResilienceCockpitService/AlternateSuppliers(ID='1627dd32-170d-47c3-b3d2-07f9a7503196',IsActiveEntity=true)/downRate
Authorization: Basic manager@nexus.com:password



### Testing SAP API Hub
GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_INFORECORD_PROCESS_SRV/A_PurchasingInfoRecord
apikey: e9XLZVe5ClNn1nCGFYgUi22BN2WYBgMW
Accept: application/json


### To read S4API
GET http://localhost:4004/service/ResilienceCockpitService/A_PurchasingInfoRecord?$filter=Material eq 'MZ-TG-A14'&$top=1
Authorization: Basic manager@nexus.com:password


###
GET http://localhost:8887/reload